<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">

<head>
<title>welcome admin..!!</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<meta name="generator" content="Web Page Maker">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>css3menu.com</title>
		<!-- Start css3menu.com HEAD section -->
	<link rel="stylesheet" href="CSS3 Menu.css3prj_files/css3menu1/style.css" type="text/css" /><style type="text/css">._css3m{display:none}</style>
	<!-- End css3menu.com HEAD section -->

</head>
<body>
<div id="html1" style="position:absolute; overflow:hidden; left:0px; top:0px; width:1347px; height:559px; z-index:0">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Carousel Gallery, Carousel Script" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:transparent">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/12617093.jpg" alt="" title="" id="wows1_0"/></li>
<li><img src="data1/images/500x500x211crime017.jpg.pagespeed.ic.ucppz0te0.jpg" alt="" title="" id="wows1_1"/></li>
<li><img src="data1/images/violencewomenii.jpg" alt="" title="" id="wows1_2"/></li>
<li><img src="data1/images/5888dfa4c92cbd9c5faba763b8e9d71f.jpg" alt="" title="" id="wows1_3"/></li>
<li><img src="data1/images/64377e3020aa627775702876a8780ee0.jpg" alt="" title="" id="wows1_4"/></li>
<li><img src="data1/images/1womanendtheviolenceiwd20132638.jpg" alt="" title="" id="wows1_5"/></li>
<li><img src="data1/images/banner1.jpg" alt="" title="" id="wows1_6"/></li>
<li><img src="data1/images/bannercommunity.jpg" alt="" title="" id="wows1_7"/></li>
<li><img src="data1/images/479c0423ebc1fbce81f00cf2aede4e5f.jpg" alt="" title="" id="wows1_8"/></li>
<li><img src="data1/images/gsanetworkliberationinkposterseries.png" alt="" title="" id="wows1_9"/></li>
<li><img src="data1/images/bannerchange.png" alt="" title="" id="wows1_10"/></li>
<li><img src="data1/images/stockvectorwomensrightsbannercrowdofdifferentwomenstandingtogetherempowermentconcept344819822.jpg" alt="" title="" id="wows1_11"/></li>
<li><img src="data1/images/banner_women.jpg" alt="" title="" id="wows1_12"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title=""><img src="data1/tooltips/12617093.jpg" alt=""/>1</a>
<a href="#" title=""><img src="data1/tooltips/500x500x211crime017.jpg.pagespeed.ic.ucppz0te0.jpg" alt=""/>2</a>
<a href="#" title=""><img src="data1/tooltips/violencewomenii.jpg" alt=""/>3</a>
<a href="#" title=""><img src="data1/tooltips/5888dfa4c92cbd9c5faba763b8e9d71f.jpg" alt=""/>4</a>
<a href="#" title=""><img src="data1/tooltips/64377e3020aa627775702876a8780ee0.jpg" alt=""/>5</a>
<a href="#" title=""><img src="data1/tooltips/1womanendtheviolenceiwd20132638.jpg" alt=""/>6</a>
<a href="#" title=""><img src="data1/tooltips/banner1.jpg" alt=""/>7</a>
<a href="#" title=""><img src="data1/tooltips/bannercommunity.jpg" alt=""/>8</a>
<a href="#" title=""><img src="data1/tooltips/479c0423ebc1fbce81f00cf2aede4e5f.jpg" alt=""/>9</a>
<a href="#" title=""><img src="data1/tooltips/gsanetworkliberationinkposterseries.png" alt=""/>10</a>
<a href="#" title=""><img src="data1/tooltips/bannerchange.png" alt=""/>11</a>
<a href="#" title=""><img src="data1/tooltips/stockvectorwomensrightsbannercrowdofdifferentwomenstandingtogetherempowermentconcept344819822.jpg" alt=""/>12</a>
<a href="#" title=""><img src="data1/tooltips/banner_women.jpg" alt=""/>13</a>
</div></div>
<span class="wsl"><a href="http://wowslider.com">Slider Web</a> by WOWSlider.com v4.8</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html></div>

<div id="image1" style="position:absolute; overflow:hidden; left:0px; top:0px; width:134px; height:91px; z-index:1"><img src="images/20160311191944.jpg" alt="" title="" border=0 width=134 height=91></div>
<br>
<br>
<br>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<br>
<br>
<br>
<br>
<br>
<br>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<body style="background-color:#EBEBEB">
<!-- Start css3menu.com BODY section -->
<ul id="css3menu1" class="topmenu">
<input type="checkbox" id="css3menu-switcher" class="switchbox"><label onclick="" class="switch" for="css3menu-switcher"></label>	<li class="topfirst"><a href="others.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/r-micon1.png" alt=""/>HOME</a></li>
	<li class="topmenu"><a href="about.html" style="height:32px;line-height:32px;"><span><img src="CSS3 Menu.css3prj_files/css3menu1/blue_circle - eye.png" alt=""/>ABOUT US</span></a>
	<ul>
		<li><a href="about.html"><span>SOFTWARE WORKING</span></a>
		<ul>
			<li><a href="gps.html">GPS DETECTION</a></li>
			<li><a href="near.html">NEAREST POLICE STATION</a></li>
			<li><a href="searchcrimecity.html">SAFEST CITY</a>
			
			
			<li><a href="searchsafestarea.html">SAFEST AREA IN RANCHI</a></li>
		</ul></li>
		<li><a href="video.html">MOTIVATIONAL VIDEOS</a></li>
		<li><a href="ngo.html">NGOs WORKING FOR US</a></li>
	</ul></li>
	<li class="topmenu"><a href="register.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/blue_circle - computer1.png" alt=""/>REGISTER</a></li>
	<li class="topmenu"><a href="complaint.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/evil.png" alt=""/>COMPLAINT</a></li>
	<li class="topmenu"><a href="gps.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/smile1.png" alt=""/>GPS/INSTANT HELP</a></li>
	<li class="topmenu"><a href="adminlogin.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/service.png" alt=""/>ADMIN</a></li>
	<li class="topmenu"><a href="loginspecial.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/user4.png" alt=""/>SPECIAL TEAM</a></li>
	<li class="topmenu"><a href="home.html" style="height:32px;line-height:32px;"><span><img src="CSS3 Menu.css3prj_files/css3menu1/help.png" alt=""/>OTHERS</span></a>
	<ul>
		<li><a href="self.html">SELF DEFENCE TECHNIQUE</a></li>
		
                          <li><a href="inspiration.html">INSPIRATIONAL VIEWS</a></li>
		<li><a href="video.html">MOTIVATIONAL VIDEOS</a></li>
	</ul></li>
	<li class="topmenu"><a href="contact.html" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/blue_circle - phone1.png" alt=""/>CONTACT US</a></li>
	<li class="toplast"><a href="submit1.jsp" style="height:32px;line-height:32px;"><img src="CSS3 Menu.css3prj_files/css3menu1/contact1.png" alt=""/>FEEDBACK</a></li>
</ul><p class="_css3m"><a href="http://css3menu.com/">css menu</a> by Css3Menu.com</p>
<!-- End css3menu.com BODY section -->


</body>
</html>

<br>
<br>
<br>
<br>
<br>
<%@page language="java"%>
<%@page import="java.sql.*"%>
<html>
<head>
</head>
<body>
<%
Connection con=null;
Statement stmt=null;
ResultSet res=null;
String name;
try
{
String id=request.getParameter("nm") ;
String password=request.getParameter("pwd");

Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

con=DriverManager.getConnection("jdbc:odbc:women");
stmt=con.createStatement();

name="select * from admin where adminname='"+id+"' and password='"+password+"'";
 
res=stmt.executeQuery(name);
if(res.next())
{
session.setAttribute("id",id);
%>
<jsp:forward page="/admin.html"/>
<%
}
else
{
%>
<jsp:forward page="/not.html"/>
<%
}
}
catch(Exception s)
{
out.println(s);
}
%>
</body>
</html>